### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException

### ISSUE THREAD

**Issue by QuinntyneBrown** [QuinntyneBrown/RenderRazorInConsoleApp#1]
@hishamco

![image](https://user-images.githubusercontent.com/1749159/42851443-bbaec016-89fa-11e8-97e2-e11beb255192.png)

**Comment by hishamco** [comment]
Let me download the source code and check the exception

**Comment by hishamco** [comment]
Seems the code that are using is outdated, could you please have a look to https://github.com/aspnet/Entropy/blob/master/samples/Mvc.RenderViewToString/Program.cs and try to rewrite your app

**Comment by QuinntyneBrown** [comment]
@hishamco  Refactored the code....still errors. :|

**Comment by hishamco** [comment]
At the first glance the code seems using old deprecated APIs such as Platform Abstractions, that is why I mentioned above to use the Entropy source code rather the one that you're using ..

**Comment by QuinntyneBrown** [comment]
This looks like  the root casue.

They use this package that is not publicly available.

![image](https://user-images.githubusercontent.com/1749159/43035200-482c4bba-8cb9-11e8-9837-7c618ebeaafd.png)

**Comment by QuinntyneBrown** [comment]
The Entropy sample in the repo works fine.

**Comment by QuinntyneBrown** [comment]
Works now.

Had to use the following in the csproj of the cli 

![image](https://user-images.githubusercontent.com/1749159/43035314-5a7bb466-8cbb-11e8-9c73-f8afafc9bd1e.png)

Trying to move the View to the core project. Not sure if that is possible

**Comment by hishamco** [comment]
Don't forgot the original source that you're using is very very old, perhaps there 're breaking changes ..

**Comment by hishamco** [comment]
> The Entropy sample in the repo works fine.
As expected!!

**Comment by QuinntyneBrown** [comment]
Do you know how to use the View from the Core project? Maybe I will have to live with what I have for now.

**Comment by hishamco** [comment]
> Maybe I will have to live with what I have for now.

Do you mean that everything is working with you right now except the view location?

**Comment by QuinntyneBrown** [comment]
Correct

**Comment by hishamco** [comment]
Could you try to use `Microsoft.NET.Sdk.Razor` instead in your Core project and use the `customApplicationBasePath` parameter in the `InitializeServices` to point to that project

**Comment by QuinntyneBrown** [comment]
Nice, it works. Where did you find the solution?

**Comment by hishamco** [comment]
I just dig into the code an there's and there's `customApplicationBasePath` parameter in the `InitializeServices` which seems did the job 😄

> Nice, it works.

All the best
